name: yamanapp
description: Adıyaman şehir rehberi uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.0.0
  google_maps_flutter: ^2.4.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.3.5
  provider: ^6.0.5
  url_launcher: ^6.1.14
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

